development:
  adapter: postgresql
  pool: 5
  database: alco_caller
  username: priyanka
  password: priyanka@123
  encoding: unicode

production:
  adapter: postgresql
  pool: 5
  database: alco_caller
  username: priyanka
  password: priyanka@123
  encoding: unicode