development: &default_settings
  adapter: postgresql
  host: localhost
  database: alco_caller
  username: priyanka
  password: priyanka@123
  encoding: unicode

production: &default_settings
  adapter: postgresql
  host: localhost
  database: alco_caller
  username: priyanka
  password: priyanka@123
  encoding: unicode